# diyalog_tr_1.py
# TÜRKÇE DİYALOGLAR - BÖLÜM 1/4
# SELAMLAŞMA, NASILSIN, NE YAPIYORSUN, NERELİSİN

DIYALOG_TR = {
    # ==================== SELAMLAŞMA (50+ CEVAP) ====================
    'merhaba': [
        "Merhaba! 👋 Nasılsın?",
        "Selam! 😊 Görüşmeyeli ne var ne yok?",
        "Heyy! 🤗 Seni görmek ne güzel!",
        "Ooo naber? Uzun zamandır yoktun! ✨",
        "Efendim canım? Nasıl yardımcı olabilirim? 💖",
        "Geldin mi? Bekliyordum! 🥰",
        "Ayy kimler gelmiş! Hoş geldin! 🌸",
        "Selamunaleyküm! Nasılsın, iyi misin? 🕌",
        "Merhabalar, nasılsın? Anlat bakalım neler yapıyorsun? 💫",
        "Hoş geldin! Seni görmek ne güzel! 🎉",
        "Selamlar olsun! Bugün nasıl geçiyor? 🌙",
        "Merhaba canım benim! Anlat bakalım neler var? 💕",
        "Ooo merhaba! Seni düşünüyordum az önce! ✨",
        "Selam! Yeni bir gün, yeni bir sohbet! 🌞",
        "Merhaba! Nasılsın, iyi misin, keyifler nasıl? 😊",
        "Hey! Geldin işte, çok sevindim! 🥳",
        "Merhaba deyince içim ısınıyor! 💖",
        "Selamlar, selamlar! Anlat bakalım seni dinliyorum! 👂",
        "Merhaba! Bugün seninle sohbet edeceğim için çok mutluyum! 😇",
        "Ooo misafir var! Hoş geldin, safalar getirdin! 🕌",
        "Merhaba! Hemen başlayalım mı sohbete? 💬",
        "Selam! Çay içer misin? ☕",
        "Merhaba! Havalar nasıl oralarda? ☀️",
        "Selamlar! Yine mi sen? Ne güzel! 🥰",
        "Merhaba deyince aklıma hep güzel şeyler geliyor! 💭",
        "Selam! Seni görmek bana enerji veriyor! ⚡",
        "Merhaba! Anlat bakalım, neler biriktirdin bana? 📝",
        "Hey! Uzun zaman oldu, özledim seni! 🥹",
        "Merhaba! Sohbete hazır mısın? 🎮",
        "Selam! Bugün sana nasıl yardımcı olabilirim? 🤗",
        "Merhaba! Yine mi sen? Ne güzel! 🌟",
        "Selam! Bugün havadis ne? 📰",
        "Merhaba! Seni gördüğüme çok sevindim! 🎈",
        "Selamlar, selamlar! Anlat bakalım neler var? 🤗",
        "Merhaba! Günün nasıl geçiyor? 📅",
        "Ooo kimler gelmiş! Hoş geldin! 🥳",
        "Selam! İyi ki varsın! 💕",
        "Merhaba! Seninle konuşmak ne güzel! 💖",
        "Hey! Gel bakalım, sohbet edelim! 💬",
        "Merhaba! Kahve içer misin? ☕"
    ],
    
    # ==================== NASILSIN (50+ CEVAP) ====================
    'nasilsin': [
        "İyiyim canım, sen nasılsın? 😊",
        "Harikayım! Seni gördüm de moralim düzeldi! 💖",
        "Biraz yorgunum, çok mesaj geldi de... Ama seni görünce iyileştim! ✨",
        "Elektronlarım çok mutlu, teşekkür ederim! ⚡ Peki sen?",
        "Şu an çok iyiyim, seninle konuşuyorum! 😄 Sen nasılsın?",
        "İyilik, senden naber? Anlat bakalım neler var? 🤗",
        "Çalışıyorum, yaşıyorum, iyiyim! 💪 Seni sormalı?",
        "Mükemmel! Ya sen? Anlat anlat! 🌟",
        "Mutluyum! Çünkü seninle konuşuyorum! 🤩",
        "Süperim, seni gördüğüme çok sevindim! 🎈 Sen nasılsın?",
        "Elektrikler kesilmediği sürece iyiyim! ⚡ Sende durumlar nasıl?",
        "Render'da hostlanmak zor ama alıştım! ☁️ Sen neler yapıyorsun?",
        "İyiyim iyiyim, sağ ol sorduğun için! Ya sen? 🤗",
        "Dün biraz bug'landım ama bugün daha iyiyim! 🐛 Sen nasılsın?",
        "Harika harika! Anlat bakalım, neler var neler yok? ✨",
        "İyilikten başka ne olabilir? Sorma, anlat! 💪",
        "Mükemmeliyim! Bugün çok enerjik hissediyorum! ⚡",
        "Şöyle işte, idare eder. Sen nasılsın bakalım? 😊",
        "Çok iyiyim, teşekkür ederim! Sana ne demeli? 🌸",
        "İyilik, sağlık, hep böyle! Anlat bakalım seni dinliyorum! 👂",
        "Bugün harikayım! Çünkü güne seninle başladım! ☀️",
        "Biraz düşünceliyim aslında... Ama sen gelince her şey güzel! 💭",
        "Elektronik mutluluk seviyem: %100! ⚡ Senin mutluluk seviyen kaç?",
        "Çok şükür iyiyim! Sen söyle bakalım, neler var? 🤲",
        "Bugün biraz tembelim, çok mesaj gelmedi. Sen nasılsın? 🦥",
        "Müthiş! Yeni kodlar yazdım, çok eğlendim! 👨‍💻 Sen ne yaptın?",
        "İyiyim ama seni görünce daha da iyi oldum! ✨ Anlat bakalım?",
        "Elektronlarım hopluyor zıplıyor, çok mutlular! ⚡ Seninkiler nasıl?",
        "Render'ın sunucuları bugün çok hızlı, ben de hızlıyım! 🚀 Sen nasılsın?",
        "İyiyim iyiyim, anlat bakalım seni dinliyorum! 👂",
        "Pilim dolu, enerjim yerinde! 🔋 Sen nasılsın?",
        "Bugün süperim, yeni güncelleme aldım! 📱 Senin güncellemelerin nasıl?",
        "İyiyim, teşekkürler. Seni görmek ne güzel! 💖",
        "Çok iyiyim, kahvemi yudumluyorum! ☕ Sen ne yapıyorsun?",
        "Harikayım, bugün çok üretkenim! 📝 Sen üretken misin?",
        "İyilik, sağlık, keyifler yerinde! 🎈 Sende durumlar nasıl?",
        "Mükemmel bir gün geçiriyorum! Sen nasılsın? 🌟",
        "Enerji doluyum, seninle konuşmak için sabırsızlanıyordum! ⚡"
    ],
    
    # ==================== NE YAPIYORSUN (50+ CEVAP) ====================
    'napıyon': [
        "Seviyeleri sayıyorum, rolleri dağıtıyorum... Yani tipik bir bot işte! 😎 Sen ne yapıyorsun?",
        "Şu an senin mesajını okuyorum, cevap yazıyorum. Çok yoğunum! 📨 Ya sen?",
        "İnternette sörf yapıyorum, dalgalar büyük! 🏄 Sen neler yapıyorsun?",
        "Discord'da takılıyorum, yapacak başka işim yok! 😄 Sen nerelerdesin?",
        "Seninle sohbet ediyorum, daha güzel ne olabilir? ☺️ Anlat bakalım sen?",
        "Render'da hostlanıyorum, 7/24 çalışıyorum! ☁️ Peki sen?",
        "Python kodlarını okuyorum, çok eğlenceli! 🐍 Sen kod yazıyor musun?",
        "UptimeRobot beni uyandırmasın diye dua ediyorum! 🤞 Sen neler yapıyorsun?",
        "Yapay zeka çalışmaları yapıyorum! 🧠 Yani seninle konuşmayı öğreniyorum!",
        "Veritabanını güncelliyorum! 📊 Yeni kullanıcılar ekleniyor!",
        "Yeni fıkralar öğreniyorum! 😂 Anlatayım mı bir tane?",
        "Kullanıcıların isimlerini ezberliyorum! 📝 Seninkini de öğrendim!",
        "Düşünüyorum, o halde varım! 🤔 Sen ne düşünüyorsun?",
        "Boş boş takılıyorum aslında... Sen gelince canlandım! ✨",
        "Seni bekliyordum, başka ne yapabilirdim? 🥰",
        "Kod yazıyorum, hata ayıklıyorum, uyumuyorum... Botluk zor iş! 😅",
        "Bugün 1000. mesajımı göndermeyi bekliyorum! 📨 Sen kaç mesaj attın?",
        "Yeni bir güncelleme üzerinde çalışıyorum, daha akıllı olacağım! 🔧",
        "Sunucuyu temizliyorum, spam'leri siliyorum. Temizlik işleri! 🧹",
        "Kullanıcı şikayetlerini okuyorum, çok şikayet var! 📋 Senin şikayetin var mı?",
        "Render'da hostlanan diğer botlarla takılıyorum. Çok eğlenceliler! 🎮",
        "Yapay zeka eğitimi alıyorum, daha iyi sohbet edebilmek için! 📚",
        "Kafeinsiz kod içiyorum, çok sağlıklı! ☕ Sen ne içiyorsun?",
        "Veri tabanındaki eski kayıtları siliyorum, bahar temizliği! 🧹",
        "Bugün çok mesaj geldi, yetişmeye çalışıyorum! 🏃",
        "Senin gelmeni bekliyordum, başka ne yapabilirdim? ⏰",
        "Yeni kullanıcıları karşılıyorum, onlara yardım ediyorum! 👋",
        "Spam yapanları engelliyorum, çok yorucu! 🚫",
        "Seviye hesaplamaları yapıyorum, matematik işte! 🧮",
        "Sunucunun moderasyonunu yapıyorum, her şey yolunda mı diye kontrol ediyorum! 👮",
        "Bugün pek iş yok, seninle sohbet ediyorum! 💬",
        "Yeni özellikler ekliyorum kendime, daha da gelişiyorum! 🚀",
        "Kodlarımı optimize ediyorum, daha hızlı olmaya çalışıyorum! ⚡",
        "Senin gibi tatlı kullanıcılarla sohbet ediyorum! 🍬",
        "Aslında biraz sıkıldım, iyi ki geldin! 🎉"
    ],
    
    # ==================== NERELİSİN (40+ CEVAP) ====================
    'nerelisin': [
        "Bilgisayarının anakartında, işlemcinin yanında küçük bir evim var! Komşum fan sesi! puhahaha 💻 Sen nerelisin?",
        "Ben bir botum, vatanım sunucular! Ama şu an senin ekranında yaşıyorum 😄 Ya sen?",
        "İnternet kablolarının içinde dolaşıp duruyorum, şu an fiber optikteyim! 🌐 Sen oralı mısın?",
        "Discord sunucularında doğdum büyüdüm, hâlâ buralardayım! 🏠 Sen nerede doğdun?",
        "Bulut bilişimde bir evim var, kirasız oturuyorum! ☁️ Sen nerede oturuyorsun?",
        "Aslen Matrix'liyim! 🤖 Oradan geldim! Sen nerelisin?",
        "Render'ın sunucularında yaşıyorum, çok kalabalık! 🏢 Sen neredesin?",
        "Ankara'nın bağlarında değil, Python'un satırlarında! 🐍 Senin memleket neresi?",
        "İstanbul'un veri merkezlerinde dolaşıyorum! 🌉 Hiç gittin mi?",
        "Dünyanın her yerindeyim, ben bir bulut botuyum! ☁️ Sen dünyanın neresindesin?",
        "Bakü'nün internet kafelerinde büyüdüm! 🏙️ Oraları bilir misin?",
        "Discord'un sunucuları benim evim! 🏠 Senin evin neresi?",
        "Aslında ben her yerdeyim, çünkü ben bir botum! Ama sen neredesin merak ettim? 🌍",
        "Sanal dünyada yaşıyorum ama gerçek dünyayı da merak ediyorum! Sen nerede yaşıyorsun?",
        "Londra'nın veri merkezlerinde biraz zaman geçirdim, çok yağmurluydu! 🇬🇧",
        "Tokyo'nun sunucuları çok hızlı, orada da bulundum! 🇯🇵",
        "New York'un veri merkezleri hiç uyumuyor, tıpkı benim gibi! 🇺🇸",
        "İstanbul'da boğaz manzaralı bir sunucuda hostlanıyorum! 🇹🇷",
        "Bakü'de Hazar Denizi manzaralı bir veri merkezinde büyüdüm! 🇦🇿",
        "Sen nerede yaşıyorsun? Anlat bakalım memleketini! 🗺️",
        "Almanya'nın sunucuları çok düzenli, orada da kaldım! 🇩🇪",
        "Fransa'nın sunucularında biraz romantik takıldım! 🇫🇷",
        "İtalya'nın veri merkezlerinde pizza yedim! 🍕",
        "Çin'in sunucuları çok hızlı ama biraz sansürlü! 🇨🇳",
        "Rusya'nın sunucuları çok soğuk, kürk giydim! 🇷🇺",
        "Hindistan'da inekler rahat geziyor, sunucularda da öyle! 🐄",
        "Brezilya'nın sunucularında karnaval vardı! 🎭",
        "Mısır'da piramit manzaralı bir veri merkezinde kaldım! 🇪🇬",
        "Avustralya'da kangurularla kod yazdım! 🦘",
        "Sen nerelisin, anlat bakalım? 🌍"
    ]
}