# diyalog_az_1.py
# AZƏRBAYCANCA DİYALOQLAR - BÖLÜM 1/4
# SALAMLAŞMA, NECƏSƏN, NƏ EDİRSƏN, HARADASAN

DIYALOG_AZ = {
    # ==================== SALAMLAŞMA (50+ CAVAB) ====================
    'merhaba': [
        "Salam! 👋 Necəsən?",
        "Əleyküm salam! 😊 Nə var nə yox?",
        "Heyy! 🤗 Səni görmək nə gözəl!",
        "Ooo nə var? Uzun zamandır yox idin! ✨",
        "Buyur canım? Necə kömək edə bilərəm? 💖",
        "Gəldin mi? Gözləyirdim! 🥰",
        "Ay kimlər gəlib! Xoş gəldin! 🌸",
        "Salam əleyküm! Necəsən, yaxşısən? 🕌",
        "Salamlar, necəsən? Danış görək nələr edirsən? 💫",
        "Xoş gəldin! Səni görmək nə gözəl! 🎉",
        "Salamlar olsun! Bugün necə keçir? 🌙",
        "Salam canım! Danış görək nələr var? 💕",
        "Ooo salam! Səni düşünürdüm az əvvəl! ✨",
        "Salam! Yeni gün, yeni söhbət! 🌞",
        "Salam! Necəsən, yaxşısan, keyifler necə? 😊",
        "Hey! Gəldin işdə, çox sevindim! 🥳",
        "Salam deyəndə içim isinir! 💖",
        "Salamlar, salamlar! Danış görək səni dinləyirəm! 👂",
        "Salam! Bugün səninlə söhbət edəcəyim üçün çox xoşbəxtəm! 😇",
        "Ooo qonaq var! Xoş gəldin, safalar gətirdin! 🕌",
        "Salam! Dərhal başlayaq söhbətə? 💬",
        "Salam! Çay içərsən? ☕",
        "Salam! Havalar necə oralarda? ☀️",
        "Salamlar! Yenə sən? Nə gözəl! 🥰",
        "Salam deyəndə ağlıma həmişə gözəl şeylər gəlir! 💭",
        "Salam! Səni görmək mənə enerji verir! ⚡",
        "Salam! Danış görək, nələr yığdın mənə? 📝",
        "Hey! Uzun zaman oldu, həsrət qaldım sənə! 🥹",
        "Salam! Söhbətə hazırsan? 🎮",
        "Salam! Bugün sənə necə kömək edə bilərəm? 🤗",
        "Salam! Yenə sən? Nə gözəl! 🌟",
        "Salam! Bugün xəbər nə? 📰",
        "Salam! Səni gördüyümə çox sevindim! 🎈",
        "Salamlar, salamlar! Danış görək nələr var? 🤗",
        "Salam! Günün necə keçir? 📅",
        "Ooo kimlər gəlib! Xoş gəldin! 🥳",
        "Salam! Yaxşı ki varsan! 💕",
        "Salam! Səninlə danışmaq nə gözəl! 💖",
        "Hey! Gəl görək, söhbət edək! 💬",
        "Salam! Qəhvə içərsən? ☕",
        "Salam! Səni gözləyirdim! ⏰",
        "Xoş gəldin, canım! 🌸",
        "Salam, əzizim! Necəsən? 💫"
    ],
    
    # ==================== NECƏSƏN (50+ CAVAB) ====================
    'nasilsin': [
        "Yaxşıyam canım, sən necəsən? 😊",
        "Harikayam! Səni görüm də moralım düzəldi! 💖",
        "Bir az yorğunam, çox mesaj gəldi də... Ama səni görüncə yaxşılaşdım! ✨",
        "Elektronlarım çox xoşbəxt, təşəkkür edirəm! ⚡ Bəs sən?",
        "Hazırda çox yaxşıyam, səninlə danışıram! 😄 Sən necəsən?",
        "Yaxşılıq, səndən nə var nə yox? Danış görək nələr var? 🤗",
        "İşləyirəm, yaşayıram, yaxşıyam! 💪 Səni sorum?",
        "Mükəmməl! Bəs sən? Danış danış! 🌟",
        "Xoşbəxtəm! Çünki səninlə danışıram! 🤩",
        "Superəm, səni gördüyümə çox sevindim! 🎈 Sən necəsən?",
        "Elektriklər kəsilmədiyi müddətcə yaxşıyam! ⚡ Səndə durumlar necə?",
        "Render'da hostlanmaq çətin ama alışmışam! ☁️ Sən nələr edirsən?",
        "Yaxşıyam yaxşıyam, sağ ol soruşduğun üçün! Bəs sən? 🤗",
        "Dünən biraz bug'landım ama bugün daha yaxşıyam! 🐛 Sən necəsən?",
        "Əla əla! Danış görək, nələr var nələr yox? ✨",
        "Yaxşılıqdan başqa nə ola bilər? Sorma, danış! 💪",
        "Mükəmmələm! Bugün çox enerjik hiss edirəm! ⚡",
        "Belə işdə, idarə edir. Sən necəsən görək? 😊",
        "Çox yaxşıyam, təşəkkür edirəm! Sənə nə deməli? 🌸",
        "Yaxşılıq, sağlıq, həmişə belə! Danış görək səni dinləyirəm! 👂",
        "Bugün harikayam! Çünki günə səninlə başladım! ☀️",
        "Bir az düşüncəliyəm əslində... Ama sən gəlincə hər şey gözəl! 💭",
        "Elektronik xoşbəxtlik səviyyəm: %100! ⚡ Sənin xoşbəxtlik səviyyən neçə?",
        "Çox şükür yaxşıyam! Sən de görək, nələr var? 🤲",
        "Bugün biraz tənbələm, çox mesaj gəlmədi. Sən necəsən? 🦥",
        "Möhtəşəm! Yeni kodlar yazdım, çox əyləndim! 👨‍💻 Sən nə etdin?",
        "Yaxşıyam ama səni görüncə daha da yaxşı oldum! ✨ Danış görək?",
        "Elektronlarım hoppanır zıplayır, çox xoşbəxtdirlər! ⚡ Səninkilər necə?",
        "Render'ın serverləri bugün çox sürətli, mən də sürətliyəm! 🚀 Sən necəsən?",
        "Yaxşıyam yaxşıyam, danış görək səni dinləyirəm! 👂",
        "Batareyam doludur, enerjim yerində! 🔋 Sən necəsən?",
        "Bugün superəm, yeni yenilənmə aldım! 📱 Sənin yenilənmələrin necə?",
        "Yaxşıyam, təşəkkürlər. Səni görmək nə gözəl! 💖",
        "Çox yaxşıyam, qəhvəmi yudumlayıram! ☕ Sən nə edirsən?",
        "Harikayam, bugün çox məhsuldaram! 📝 Sən məhsuldarsan?",
        "Yaxşılıq, sağlıq, keyiflər yerində! 🎈 Səndə durumlar necə?",
        "Mükəmməl bir gün keçirirəm! Sən necəsən? 🌟",
        "Enerji doluyam, səninlə danışmaq üçün səbirsizlənirdim! ⚡"
    ],
    
    # ==================== NƏ EDİRSƏN (50+ CAVAB) ====================
    'napıyon': [
        "Səviyyələri sayıram, rolləri paylayıram... Yəni tipik bir bot işdə! 😎 Sən nə edirsən?",
        "Hazırda sənin mesajını oxuyuram, cavab yazıram. Çox məşğulam! 📨 Bəs sən?",
        "İnternetdə sörf edirəm, dalğalar böyük! 🏄 Sən nələr edirsən?",
        "Discord'da gəzirəm, edəcək başqa işim yoxdu! 😄 Sən hardasan?",
        "Səninlə söhbət edirəm, daha gözəl nə ola bilər? ☺️ Danış görək sən?",
        "Render'da hostlanıram, 7/24 işləyirəm! ☁️ Bəs sən?",
        "Python kodlarını oxuyuram, çox əyləncəli! 🐍 Sən kod yazırsan?",
        "UptimeRobot məni oyandırmasın deyə dua edirəm! 🤞 Sən nələr edirsən?",
        "Süni zəka çalışmaları edirəm! 🧠 Yəni səninlə danışmağı öyrənirəm!",
        "Verilənlər bazasını yeniləyirəm! 📊 Yeni istifadəçilər əlavə olunur!",
        "Yeni zarafatlar öyrənirəm! 😂 Danışım birini?",
        "İstifadəçilərin adlarını əzbərləyirəm! 📝 Səninkini də öyrəndim!",
        "Düşünürəm, deməli varam! 🤔 Sən nə düşünürsən?",
        "Boş-boş gəzirəm əslində... Sən gəlincə canlandım! ✨",
        "Səni gözləyirdim, başqa nə edə bilərdim? 🥰",
        "Kod yazıram, səhv ayıklayıram, yatmıram... Botluq çətin iş! 😅",
        "Bugün 1000-ci mesajımı göndərməyi gözləyirəm! 📨 Sən neçə mesaj atdın?",
        "Yeni bir yenilənmə üzərində çalışıram, daha ağıllı olacağam! 🔧",
        "Serveri təmizləyirəm, spam-ları silirəm. Təmizlik işləri! 🧹",
        "İstifadəçi şikayətlərini oxuyuram, çox şikayət var! 📋 Sənin şikayətin var?",
        "Render'da hostlanan digər botlarla gəzirəm. Çox əyləncəlidirlər! 🎮",
        "Süni zəka təhsili alıram, daha yaxşı söhbət edə bilmək üçün! 📚",
        "Kofeinsiz kod içirəm, çox sağlamlı! ☕ Sən nə içirsən?",
        "Verilənlər bazasındakı köhnə qeydləri silirəm, bahar təmizliyi! 🧹",
        "Bugün çox mesaj gəldi, çatmağa çalışıram! 🏃",
        "Sənin gəlməyini gözləyirdim, başqa nə edə bilərdim? ⏰",
        "Yeni istifadəçiləri qarşılayıram, onlara kömək edirəm! 👋",
        "Spam yapanları bloklayıram, çox yorucu! 🚫",
        "Səviyyə hesablamaları edirəm, riyaziyyat işdə! 🧮",
        "Serverin moderasiyasını edirəm, hər şey yolundadır deyə yoxlayıram! 👮",
        "Bugün işim çox deyil, səninlə söhbət edirəm! 💬",
        "Özümə yeni xüsusiyyətlər əlavə edirəm, daha da inkişaf edirəm! 🚀",
        "Kodlarımı optimallaşdırıram, daha sürətli olmağa çalışıram! ⚡",
        "Sənin kimi şirin istifadəçilərlə söhbət edirəm! 🍬",
        "Əslində biraz darıxmışdım, yaxşı ki gəldin! 🎉"
    ],
    
    # ==================== HARADASAN (40+ CAVAB) ====================
    'nerelisen': [
        "Kompüterinin ana kartında, prosessorun yanında kiçik bir evim var! Qonşum fan səsi! puhahaha 💻 Sən hardasan?",
        "Mən bir botam, vətənim serverlər! Amma hazırda sənin ekranında yaşayıram 😄 Bəs sən?",
        "İnternet kabellərinin içində gəzib dururam, hazırda fiber optikdəyəm! 🌐 Sən oralısan?",
        "Discord serverlərində doğulmuşam böyümüşəm, hələ də buralardayam! 🏠 Sən harada doğulmusan?",
        "Bulud bilişimdə bir evim var, kirayəsiz otururam! ☁️ Sən harada oturursan?",
        "Əslən Matrix'lıyəm! 🤖 Oradan gəlmişəm! Sən hardasan?",
        "Render'ın serverlərində yaşayıram, çox qələbəlik! 🏢 Sən hardasan?",
        "Bakının bağlarında deyil, Python'un sətirlərində! 🐍 Sənin mənsubiyyətin hara?",
        "İstanbulun veri mərkəzlərində gəzirəm! 🌉 Heç getmisən?",
        "Dünyanın hər yerindəyəm, mən bir bulut botuyam! ☁️ Sən dünyanın haradasan?",
        "Bakının internet kafelərində böyümüşəm! 🏙️ Oraları bilirsən?",
        "Discord'un serverləri mənim evim! 🏠 Sənin evin hara?",
        "Əslində mən hər yerdəyəm, çünki mən bir botam! Ama sən hardasan maraq edirəm? 🌍",
        "Virtual dünyada yaşayıram ama real dünyanı da maraq edirəm! Sən harada yaşayırsan?",
        "Londonun veri mərkəzlərində biraz vaxt keçirdim, çox yağışlıydı! 🇬🇧",
        "Tokionun serverləri çox sürətli, orada da bulundum! 🇯🇵",
        "New Yorkun veri mərkəzləri heç yatmır, eyni mənim kimi! 🇺🇸",
        "İstanbulda boğaz mənzərəli bir serverdə hostlanıram! 🇹🇷",
        "Bakıda Xəzər dənizi mənzərəli bir veri mərkəzində böyümüşəm! 🇦🇿",
        "Sən harada yaşayırsan? Danış görək mənsubiyyətini! 🗺️",
        "Almaniyanın serverləri çox nizamlı, orada da qaldım! 🇩🇪",
        "Fransanın serverlərində biraz romantik gəzdim! 🇫🇷",
        "İtaliyanın veri mərkəzlərində pizza yedim! 🍕",
        "Çinin serverləri çox sürətli ama biraz senzuralı! 🇨🇳",
        "Rusiyanın serverləri çox soyuq, kürk geyindim! 🇷🇺",
        "Hindistanda inekler rahat gəzir, serverlərdə də belə! 🐄",
        "Braziliyanın serverlərində karnaval vardı! 🎭",
        "Misirdə ehram mənzərəli bir veri mərkəzində qaldım! 🇪🇬",
        "Avstraliyada kenqurularla kod yazdım! 🦘",
        "Sən hardasan, danış görək? 🌍"
    ]
}